engines:
  rubocop:
    enabled: false
  coffeelint:
    enabled: true
  fixme:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  scss-lint:
    enabled: false
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
        - ruby
        - javascript

  foodcritic:
    enabled: false
ratings:
  paths:
    - app/**
    - lib/**
    - '**.rb'
    - '**.go'
exclude_paths:
  - vendor/**/*
  - db/**/*
  - app/assets/fonts/**/*
  - public/**/*
  - bin/**/*
  - '**.jpg'
  - '**.wsdl'
  - '**.svg'
  - '**.png'
  - '**.gif'
  - '**.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
